include:
  - path:
      - docker-compose.authentik.yml
      - ./authentik-overrides.yml

services:
  web:
    build:
      context: ./web
    expose:
      - 5173
    labels:
      traefik.enable: true
      traefik.http.routers.web.rule: Host(`web.${BASE_DOMAIN}`)
      traefik.http.routers.web.entrypoints: websecure
      traefik.http.routers.web.tls: true

  traefik:
    image: traefik
    restart: always
    command:
      # enable logs on every request
      - --accesslog=true
      # enable the traefik dashboard service
      - --api.dashboard=true
      # expose ports
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      # redirect http -> https
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      # read docker labels for host configurations
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
    labels:
      # shared configurations
      traefik.http.middlewares.csp-header.headers.customresponseheaders.content-security-policy: "frame-ancestors *;"
      # traefik container config
      traefik.enable: "true"
      traefik.http.routers.traefik.rule: "Host(`traefik.${BASE_DOMAIN:?Please set BASE_DOMAIN in .env file.}`)"
      traefik.http.routers.traefik.tls: "true"
      traefik.http.routers.traefik.service: "api@internal"
      traefik.http.routers.traefik.entrypoints: websecure
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"